# Generated by Django 3.0.7 on 2020-08-01 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_auto_20200801_0041'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='tag',
            new_name='Category',
        ),
    ]
