# Generated by Django 3.0.7 on 2020-08-06 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_auto_20200801_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imgurl',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
