# Generated by Django 3.0.7 on 2020-08-06 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='item_id',
            new_name='product_id',
        ),
    ]
